[package]
name = "japan-area-db-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
scraper = "0.22.0"
tokio = { version = "1", features = ["full"] }
rusqlite = { version = "0.32.0", features = ["bundled"] }